package com.imera.censo.Contracts.Enums;

public enum Opr_UsuariosEnum {
    id
    ,id_padron
    ,id_cuenta
    ,id_carga
    ,id_censista
    ,id_servicio
    ,id_tipousuario
    ,medidor_ins
    ,lectura_med_ins
    ,id_marca_ins
    ,id_modelo_ins
    ,id_diametro
    ,id_materialtoma
    ,id_tipotoma
    ,id_tipoglobo
    ,id_mat_banqueta
    ,id_mat_calle
    ,registro_banqueta
    ,id_anomalia
    ,fac_tecnica
    ,tinaco
    ,cisterna
    ,alberca
    ,pozo
    ,foto_predio
    ,foto_toma
    ,nombre_comercial
    ,observa_a
    ,id_giro
    ,id_calle_ppal
    ,id_calle_lat1
    ,id_calle_lat2
    ,latitud
    ,longitud
    ,id_estatus
    ,id_identificacion
    ,id_colonia
    ,direccion
    ,nombre
    ,num_int
    ,num_ext
    ,otro
}
